# Generated by Django 5.2.8 on 2025-12-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_user_otp_attempts_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='Cloudinary public_id', max_length=500, null=True),
        ),
    ]
