# Generated by Django 5.2.8 on 2026-02-05 09:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_productvariant_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off cart'), ('fixed', 'Fixed amount off cart'), ('free_shipping', 'Free shipping')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_cart_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum subtotal to qualify', max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed_per_item', 'Fixed per item')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_items', models.PositiveSmallIntegerField(default=1, help_text='Minimum quantity in cart to qualify')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_offer', to='products.category')),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts', max_digits=12, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_offer', to='products.product')),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
                'abstract': False,
            },
        ),
    ]
