# Generated by Django 5.2.8 on 2026-02-07 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_productoffer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaloffer',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
