# Generated by Django 5.2.8 on 2026-02-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_globaloffer_value'),
        ('products', '0002_product_productvariant_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='products.category'),
        ),
    ]
