# Generated by Django 5.2.8 on 2026-02-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_categoryoffer_category'),
        ('products', '0002_product_productvariant_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='products.product'),
        ),
    ]
