# Generated by Django 5.2.8 on 2026-03-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_productoffer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='min_items',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage')], default='percent', max_length=20),
        ),
    ]
