# Generated by Django 5.2.8 on 2026-01-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_invoice'),
        ('return', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created_at'], 'verbose_name': 'Return Request', 'verbose_name_plural': 'Return Requests'},
        ),
        migrations.AddField(
            model_name='return',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin regarding acceptance/rejection'),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_reason',
            field=models.TextField(help_text='Overall reason for the return request'),
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units being returned')),
                ('item_reason', models.TextField(blank=True, help_text='Specific reason for returning this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='order.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='return.return')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'constraints': [models.UniqueConstraint(fields=('return_request', 'order_item'), name='unique_order_item_per_return')],
            },
        ),
    ]
