# Generated by Django 5.2.8 on 2026-01-29 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_alter_return_options_return_admin_notes_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='return',
            new_name='returns_ret_status_ba42d4_idx',
            old_name='return_retu_status_891303_idx',
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='returns.return'),
        ),
    ]
