# Generated by Django 5.2.8 on 2026-03-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desktop_image', models.URLField()),
                ('mobile_image', models.URLField(blank=True, null=True)),
                ('redirect_link', models.URLField(blank=True)),
                ('location', models.CharField(choices=[('home_hero', 'Home Hero'), ('home_secondary', 'Home Secondary')], max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
