# Generated by Django 5.2.8 on 2026-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='desktop_public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
