# Generated by Django 5.2.8 on 2026-03-17 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_banner_desktop_public_id_banner_mobile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
