# Generated by Django 5.2.8 on 2026-02-25 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productvariant_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
