# Generated by Django 5.2.8 on 2026-02-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_pro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_id',
        ),
    ]
