# Generated by Django 5.2.8 on 2026-02-25 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_pro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
