# Generated by Django 5.2.8 on 2026-02-25 04:31

from django.db import migrations
import uuid


def fill_unique_uuids(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.filter(pro_id='1cc475c0-d57f-4be7-adef-289d995d3443').iterator():
        product.pro_id = uuid.uuid4()
        product.save(update_fields=['pro_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_pro_id'),
    ]

    operations = [
        migrations.RunPython(fill_unique_uuids, migrations.RunPython.noop)
    ]
