# Generated by Django 5.2.8 on 2026-02-25 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_populate_pro_id_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
