# Generated by Django 5.2.8 on 2026-01-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('online', 'Online'), ('wallet', 'Wallet')], default='COD', max_length=50),
        ),
    ]
