# Generated by Django 5.2.8 on 2026-03-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_productreview_productreviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
    ]
