# Generated by Django 5.2.8 on 2026-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
